import os
from datetime import datetime
from fpdf import FPDF


class PDFReport(FPDF):
    """PDF report generator for vulnerability scan results."""
    
    # Severity colors
    SEVERITY_COLORS = {
        'CRITICAL': (255, 68, 68),    # Red
        'HIGH': (255, 136, 0),        # Orange
        'MEDIUM': (255, 204, 0),       # Yellow
        'LOW': (68, 204, 68),          # Green
        'NONE': (128, 128, 128)        # Gray
    }
    
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
    
    def header(self):
        """Add header to each page."""
        if self.page_no() > 1:
            self.set_font('Arial', 'B', 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 10, 'Vulnerability Scan Report', 0, 0, 'L')
            self.cell(0, 10, f'Page {self.page_no()}', 0, 1, 'R')
            self.ln(5)
    
    def footer(self):
        """Add footer to each page."""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Generated by NetScan - For authorized use only', 0, 0, 'C')
    
    def add_title_page(self, target, scan_date, total_ports, cve_summary):
        """
        Add the title page to the report.
        
        Args:
            target: The scanned target
            scan_date: Date and time of the scan
            total_ports: Total number of open ports
            cve_summary: Dictionary with counts of each severity level
        """
        self.add_page()
        
        # Title
        self.set_font('Arial', 'B', 24)
        self.set_text_color(0, 0, 0)
        self.ln(60)
        self.cell(0, 20, 'Vulnerability Scan Report', 0, 1, 'C')
        
        # Subtitle line
        self.set_draw_color(88, 166, 255)
        self.set_line_width(1)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(20)
        
        # Target information
        self.set_font('Arial', '', 12)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, f'Target: {target}', 0, 1, 'C')
        self.cell(0, 10, f'Scan Date: {scan_date}', 0, 1, 'C')
        self.ln(20)
        
        # Summary section
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, 'Scan Summary', 0, 1, 'C')
        self.ln(5)
        
        # Open ports count
        self.set_font('Arial', '', 12)
        self.cell(0, 8, f'Open Ports Found: {total_ports}', 0, 1, 'C')
        self.ln(10)
        
        # CVE summary section
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'CVE Summary', 0, 1, 'C')
        self.ln(2)
        
        # Severity counts table
        col_width = 35
        start_x = (210 - (col_width * 5)) / 2
        
        severities = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'NONE']
        
        # Header row with severity colors
        self.set_x(start_x)
        for severity in severities:
            color = self.SEVERITY_COLORS.get(severity, (128, 128, 128))
            self.set_fill_color(*color)
            self.set_text_color(255, 255, 255)
            self.set_font('Arial', 'B', 10)
            self.cell(col_width, 10, severity, 1, 0, 'C', True)
        self.ln()
        
        # Count row
        self.set_x(start_x)
        self.set_text_color(0, 0, 0)
        self.set_font('Arial', '', 12)
        for severity in severities:
            count = cve_summary.get(severity.lower(), 0)
            self.cell(col_width, 10, str(count), 1, 0, 'C')
        self.ln()
    
    def add_port_section(self, port_data, cves):
        """
        Add a section for a single port with its CVEs.
        
        Args:
            port_data: Dictionary with port information
            cves: List of CVE dictionaries for this port
        """
        self.add_page()
        
        # Port header
        port = port_data['port']
        protocol = port_data['protocol']
        service = port_data['service']
        product = port_data.get('product', '')
        version = port_data.get('version', '')
        extrainfo = port_data.get('extrainfo', '')
        banner = port_data.get('banner', '')
        
        self.set_font('Arial', 'B', 16)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, f'Port {port}/{protocol}', 0, 1)
        
        # Service details
        self.set_font('Arial', '', 11)
        self.cell(0, 6, f'Service: {service}', 0, 1)
        
        if product:
            self.cell(0, 6, f'Product: {product}', 0, 1)
        
        if version:
            self.cell(0, 6, f'Version: {version}', 0, 1)
        
        if extrainfo:
            self.cell(0, 6, f'Extra Info: {extrainfo}', 0, 1)
        
        if banner:
            self.set_font('Arial', 'I', 10)
            self.cell(0, 6, f'Banner: {banner[:100]}', 0, 1)
        
        self.ln(10)
        
        # CVEs section
        if cves:
            self.set_font('Arial', 'B', 12)
            self.cell(0, 10, f'CVEs Found: {len(cves)}', 0, 1)
            self.ln(2)
            
            # CVE table header
            self.set_fill_color(88, 166, 255)
            self.set_text_color(255, 255, 255)
            self.set_font('Arial', 'B', 10)
            self.set_draw_color(64, 64, 64)
            
            # Column widths
            id_width = 30
            desc_width = 80
            score_width = 25
            severity_width = 30
            date_width = 25
            
            self.cell(id_width, 8, 'CVE ID', 1, 0, 'C', True)
            self.cell(desc_width, 8, 'Description', 1, 0, 'C', True)
            self.cell(score_width, 8, 'CVSS Score', 1, 0, 'C', True)
            self.cell(severity_width, 8, 'Severity', 1, 0, 'C', True)
            self.cell(date_width, 8, 'Published', 1, 1, 'C', True)
            
            # CVE table rows
            self.set_text_color(0, 0, 0)
            self.set_font('Arial', '', 9)
            
            for cve in cves:
                # Set background color based on severity
                severity = cve.get('severity', 'NONE')
                color = self.SEVERITY_COLORS.get(severity, (128, 128, 128))
                self.set_fill_color(*color)
                self.set_text_color(255, 255, 255)
                
                # CVE ID
                self.set_font('Arial', 'B', 9)
                self.cell(id_width, 8, cve.get('id', 'Unknown'), 1, 0, 'C', True)
                
                # Description (truncated to fit)
                self.set_fill_color(255, 255, 255)
                self.set_text_color(0, 0, 0)
                self.set_font('Arial', '', 8)
                desc = cve.get('description', '')[:75]
                if len(cve.get('description', '')) > 75:
                    desc += '...'
                self.cell(desc_width, 8, desc, 1, 0, 'L', True)
                
                # CVSS Score
                score = cve.get('cvss_score', 0)
                self.cell(score_width, 8, f'{score:.1f}', 1, 0, 'C', True)
                
                # Severity (colored background)
                self.set_fill_color(*color)
                self.set_text_color(255, 255, 255)
                self.cell(severity_width, 8, severity, 1, 0, 'C', True)
                
                # Published date
                self.set_fill_color(255, 255, 255)
                self.set_text_color(0, 0, 0)
                self.cell(date_width, 8, cve.get('published', 'Unknown'), 1, 1, 'C', True)
        else:
            self.set_font('Arial', 'I', 11)
            self.set_text_color(100, 100, 100)
            self.cell(0, 10, 'No CVEs found for this service.', 0, 1)


def generate_report(scan_results, report_path='reports'):
    """
    Generate a PDF report from scan results.
    
    Args:
        scan_results: Dictionary with scan results including open ports and CVEs
        report_path: Directory path for saving the report
    
    Returns:
        Path to the generated PDF file
    """
    # Create reports directory if it doesn't exist
    os.makedirs(report_path, exist_ok=True)
    
    # Extract scan information
    target = scan_results.get('target', 'Unknown')
    scan_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    open_ports = scan_results.get('open_ports', [])
    total_ports = len(open_ports)
    
    # Calculate CVE summary
    cve_summary = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0, 'none': 0}
    
    for port in open_ports:
        for cve in port.get('cves', []):
            severity = cve.get('severity', 'NONE').lower()
            if severity in cve_summary:
                cve_summary[severity] += 1
    
    # Generate filename
    safe_target = target.replace('/', '_').replace('\\', '_')
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"scan_{safe_target}_{timestamp}.pdf"
    filepath = os.path.join(report_path, filename)
    
    # Create PDF
    pdf = PDFReport()
    
    # Add title page
    pdf.add_title_page(target, scan_date, total_ports, cve_summary)
    
    # Add port sections
    for port_data in open_ports:
        cves = port_data.get('cves', [])
        pdf.add_port_section(port_data, cves)
    
    # Save the PDF
    pdf.output(filepath)
    
    return filepath, filename
